# Form implementation generated from reading ui file 'D:\BadmintonManagement\dangky_dangnhap\popup_thanh_vien.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton_dang_ky = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_dang_ky.setGeometry(QtCore.QRect(80, 90, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dang_ky.setFont(font)
        self.pushButton_dang_ky.setObjectName("pushButton_dang_ky")
        self.pushButton_dang_nhap_nhanh = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_dang_nhap_nhanh.setGeometry(QtCore.QRect(80, 170, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dang_nhap_nhanh.setFont(font)
        self.pushButton_dang_nhap_nhanh.setObjectName("pushButton_dang_nhap_nhanh")
        self.pushButton_dong = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_dong.setGeometry(QtCore.QRect(300, 10, 93, 28))
        self.pushButton_dong.setObjectName("pushButton_dong")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_dang_ky.setText(_translate("Dialog", "Đăng ký"))
        self.pushButton_dang_nhap_nhanh.setText(_translate("Dialog", "Đặt sân nhanh"))
        self.pushButton_dong.setText(_translate("Dialog", "Đóng"))
