# Form implementation generated from reading ui file 'D:\BadmintonManagement\app_admin\views_admin\ui_files\popup_cap_nhat_mk.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_popup_cap_nhap_mk(object):
    def setupUi(self, popup_cap_nhap_mk):
        popup_cap_nhap_mk.setObjectName("popup_cap_nhap_mk")
        popup_cap_nhap_mk.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=popup_cap_nhap_mk)
        self.label.setGeometry(QtCore.QRect(90, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=popup_cap_nhap_mk)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=popup_cap_nhap_mk)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_dong = QtWidgets.QPushButton(parent=popup_cap_nhap_mk)
        self.pushButton_dong.setGeometry(QtCore.QRect(322, 8, 61, 31))
        self.pushButton_dong.setObjectName("pushButton_dong")
        self.pushButton_cap_nhat = QtWidgets.QPushButton(parent=popup_cap_nhap_mk)
        self.pushButton_cap_nhat.setGeometry(QtCore.QRect(150, 230, 93, 28))
        self.pushButton_cap_nhat.setObjectName("pushButton_cap_nhat")
        self.lineEdit_mk_moi = QtWidgets.QLineEdit(parent=popup_cap_nhap_mk)
        self.lineEdit_mk_moi.setGeometry(QtCore.QRect(210, 120, 151, 22))
        self.lineEdit_mk_moi.setObjectName("lineEdit_mk_moi")
        self.lineEdit_xac_nhan_mk_moi = QtWidgets.QLineEdit(parent=popup_cap_nhap_mk)
        self.lineEdit_xac_nhan_mk_moi.setGeometry(QtCore.QRect(210, 160, 151, 22))
        self.lineEdit_xac_nhan_mk_moi.setObjectName("lineEdit_xac_nhan_mk_moi")

        self.retranslateUi(popup_cap_nhap_mk)
        QtCore.QMetaObject.connectSlotsByName(popup_cap_nhap_mk)

    def retranslateUi(self, popup_cap_nhap_mk):
        _translate = QtCore.QCoreApplication.translate
        popup_cap_nhap_mk.setWindowTitle(_translate("popup_cap_nhap_mk", "Dialog"))
        self.label.setText(_translate("popup_cap_nhap_mk", "Cập nhật mật khẩu "))
        self.label_2.setText(_translate("popup_cap_nhap_mk", "Mật khẩu mới "))
        self.label_3.setText(_translate("popup_cap_nhap_mk", "Xác nhận mật khẩu mới "))
        self.pushButton_dong.setText(_translate("popup_cap_nhap_mk", "Đóng"))
        self.pushButton_cap_nhat.setText(_translate("popup_cap_nhap_mk", "Cập nhật "))
