# Form implementation generated from reading ui file 'D:\BadmintonManagement\app_admin\views_admin\ui_files\popup_trang_thai.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dateTimeEdit_gio_bat_dau = QtWidgets.QDateTimeEdit(parent=Dialog)
        self.dateTimeEdit_gio_bat_dau.setGeometry(QtCore.QRect(160, 110, 194, 22))
        self.dateTimeEdit_gio_bat_dau.setObjectName("dateTimeEdit_gio_bat_dau")
        self.dateTimeEdit_gio_ket_thuc = QtWidgets.QDateTimeEdit(parent=Dialog)
        self.dateTimeEdit_gio_ket_thuc.setGeometry(QtCore.QRect(160, 160, 194, 22))
        self.dateTimeEdit_gio_ket_thuc.setObjectName("dateTimeEdit_gio_ket_thuc")
        self.pushButton_dong = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_dong.setGeometry(QtCore.QRect(320, 10, 71, 21))
        self.pushButton_dong.setObjectName("pushButton_dong")
        self.pushButton_dat_san = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_dat_san.setGeometry(QtCore.QRect(250, 210, 93, 28))
        self.pushButton_dat_san.setObjectName("pushButton_dat_san")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(160, 70, 55, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Trạng thái sân "))
        self.label_2.setText(_translate("Dialog", "Giờ bắt đầu"))
        self.label_3.setText(_translate("Dialog", "Giờ kết thúc"))
        self.pushButton_dong.setText(_translate("Dialog", "Đóng"))
        self.pushButton_dat_san.setText(_translate("Dialog", "Đặt sân "))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
